tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "tertiary-fixed": "#e5e2e1",
                "secondary-container": "#04b71a",
                "primary-fixed-dim": "#77dd6a",
                "tertiary": "#c8c6c5",
                "surface": "#121414",
                "on-error": "#690005",
                "surface-container": "#1e2020",
                "primary-container": "#3fa539",
                "surface-container-low": "#1a1c1c",
                "primary-fixed": "#92fa83",
                "on-tertiary": "#313030",
                "on-tertiary-container": "#2a2a2a",
                "outline": "#899483",
                "secondary-fixed-dim": "#4ce346",
                "secondary-fixed": "#75ff68",
                "error": "#ffb4ab",
                "tertiary-container": "#929090",
                "primary": "#77dd6a",
                "on-secondary-fixed": "#002201",
                "on-error-container": "#ffdad6",
                "on-primary-container": "#003202",
                "surface-variant": "#333535",
                "on-background": "#e2e2e2",
                "on-primary-fixed": "#002201",
                "on-surface": "#e2e2e2",
                "on-surface-variant": "#becab7",
                "tertiary-fixed-dim": "#c8c6c5",
                "on-tertiary-fixed": "#1c1b1b",
                "inverse-primary": "#006e0c",
                "outline-variant": "#3f4a3b",
                "surface-dim": "#121414",
                "surface-tint": "#77dd6a",
                "secondary": "#4ce346",
                "on-primary-fixed-variant": "#005307",
                "surface-container-lowest": "#0c0f0f",
                "on-primary": "#003a03",
                "on-secondary-container": "#003f03",
                "inverse-surface": "#e2e2e2",
                "on-tertiary-fixed-variant": "#474746",
                "surface-container-high": "#282a2b",
                "error-container": "#93000a",
                "surface-bright": "#38393a",
                "on-secondary-fixed-variant": "#005306",
                "on-secondary": "#003a03",
                "background": "#121414",
                "surface-container-highest": "#333535",
                "inverse-on-surface": "#2f3131"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-desktop": "80px",
                "container-max": "1440px",
                "margin-mobile": "20px",
                "gutter": "24px",
                "unit": "4px"
            },
            "fontFamily": {
                "body-md": ["Inter"],
                "headline-xl-mobile": ["Montserrat"],
                "headline-xl": ["Montserrat"],
                "headline-md": ["Montserrat"],
                "body-lg": ["Inter"],
                "headline-lg": ["Montserrat"],
                "headline-lg-mobile": ["Montserrat"],
                "label-bold": ["Inter"]
            },
            "fontSize": {
                "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-xl-mobile": ["40px", {"lineHeight": "1.1", "fontWeight": "800"}],
                "headline-xl": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
                "label-bold": ["14px", {"lineHeight": "1.2", "fontWeight": "600"}]
            }
        },
    },
}